### PR TITLE
Implemented support for new NSLayoutConstraint's active property

### PR DESCRIPTION
**Pull request by kovpas**
This also resolves issue #101, as you can activate/deactivate constraints as many times as you wish.

### CODE REVIEW

**Comment by cloudkite** [comment]
@kovpas Sorry for the delay! didn't realise this was still open. I would rather have a separate active/deactivate methods, which fallback to install/uninstall rather than modify the existing install/uninstall methods as semantically these two sets of operations are quite different.

Also I would remove the `ifdef __IPHONE_8_0` checks since you are already testing whether NSLayoutConstraint responds to the active selector

**Comment by kovpas** [comment]
@cloudkite I think in 95% of cases it would be ok to use "merged" version of active/install, but in case if layout changes dramatically (i.e. common closest superview changes), it would be nice to uninstall constraint completely, indeed.

Re `__IPHONE_8_0` checks, I'd still have at least check that project has been compiled with iOS 8+ SDK, as `active` property is not available in iOS 7 and below.

**Comment by cloudkite** [comment]
@kovpas looking good, Thanks!

I still don't think the `__IPHONE_8_0` checks are necessary. Since as long as your project uses iOS 8+ as the base SDK you could still set a lower iOS deployment target of > 8 and it should compile fine.

Also please put opening braces on same line as if statement for consistency with rest of code base

**Comment by kovpas** [comment]
@cloudkite I'd still leave check for iOS8, since it's still technically possible to ship apps with Xcode 5.1 and iOS 7 SDK... Even more, I'd even have added check for `__MAC_10_10` to make sure that Masonry is still supported for OS X 10.9 SDK. Please let me know if you've got strong objections against that.

Regarding opening braces - sorry, tried to write new code in a consistent manner, but sometimes habits were stronger :)

**Comment by kovpas** [comment]
And another note, may be this version should be 0.6.0, not 0.5.4, as long as there's new API - activate/deactivate. What do you think?

**Comment by cloudkite** [comment]
@kovpas yeah 0.6.0 sounds good

cluttering the code with availability checks just to support a small fraction of users who might be still on xcode 5 is not ideal. If you are not upgrading your xcode chances are your probably not upgrading your dependencies either

**Comment by kovpas** [comment]
@cloudkite agree. Done.

**Comment by cloudkite** [comment]
@kovpas Thanks alot!

Made one small change https://github.com/Masonry/Masonry/commit/cd4849649079ba8cbd46991d2a6f44f32a799932

**Comment by kovpas** [comment]
@cloudkite Travis can't build it anymore:

```
error: no visible @interface for 'MASLayoutConstraint' declares the selector 'isActive'
```

I suppose this happens because of using `iphonesimulator7.0` sdk in `.travis.yml`

```
$ xctool -workspace 'Masonry.xcworkspace' -scheme 'Masonry iOS Tests' -configuration Debug -sdk iphonesimulator7.0 clean build test ARCHS=i386 VALID_ARCHS=i386 ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
```

**Comment by cloudkite** [comment]
@kovpas cool thanks have updated it to `iphonesimulator8.1` and its passing now. Thanks again :)

**Comment by kovpas** [comment]
@cloudkite thank you!

**Comment by kovpas** [comment]
@cloudkite Sorry for bothering you, one last thing - could you please make a tag `v0.6.0` and upload update to cocoapods? :)

**Comment by cloudkite** [comment]
@kovpas cool done :+1:

**Pull request merged**
